### ISSUE TITLE
Hide Text and Buttons on inactive windows

### ISSUE THREAD

**Issue by DonK5hot** [ju1464/Simply_Circles_Themes#1]
I'm trying to modify Simply Circles Dark to use color #182224 for active titlebar, #1c2122 for inactive (titlebar, text and buttons), similar to what you can do with Breeze settings.
So, inactive windows would just show the frame with no text or buttons.

I copied the dark theme to ~/.local/share/aurorae/themes/Simply_Circles_Dark2, searched and replaced for the colors, didn't get it to work. 
Colors stayed the same, buttons changed (see screenshot).
![Screenshot_20190807_102211](https://user-images.githubusercontent.com/20594703/62607509-7bd0db80-b8fe-11e9-8b3f-0e99bcf40ac9.png)

Can you take a look? I think that the Hide Inactive could be a cool feature, and some additional README section on how to configure the colors yourself would help.

**Comment by ju1464** [comment]
To change the colors you must edit the svg and rc files, and if you change the name you must also change it in the metadata file.
